project:
  type: book

book:
  title: "Data-Science Reactivity: Three Ways"
  author: "Ian Lyttle"
  chapters:
    - index.qmd
    - shiny.qmd
    - dash.qmd
    - observable.qmd
  appendices:
    - field-guide-python.qmd
    - deployment.qmd
    - stray-thoughts.qmd

date: today
date-format: "YYYY-MM-DD"

bibliography: references.bib

format:
  html:
    css: nocheckbox.css
    theme:
      light: sandstone
      dark: [slate, theme-dark.scss]
    include-in-header:
      - img-filter.html
